
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oversii.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Property
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Property()
    {

        this.Citations = new HashSet<Citation>();

        this.ManagerRequests = new HashSet<ManagerRequest>();

        this.ProperytViolations = new HashSet<ProperytViolation>();

        this.Variences = new HashSet<Varience>();

        this.Residents = new HashSet<Resident>();

    }


    public int PropID { get; set; }

    public string PropertyName { get; set; }

    public Nullable<int> PropertyMgmtID { get; set; }

    public bool Active { get; set; }

    public string ParkingGL { get; set; }

    public bool PropertyManagerEditing { get; set; }

    public bool C24HrGracePeriod { get; set; }

    public bool AssignedParkingSpace { get; set; }

    public bool OverSiiSendingLetterFines { get; set; }

    public bool HasPM { get; set; }

    public int AudittrailID { get; set; }

    public int HistoryTrackingTypeID { get; set; }



    public virtual Audittrail Audittrail { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Citation> Citations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ManagerRequest> ManagerRequests { get; set; }

    public virtual PropertyHistoryTrackingType PropertyHistoryTrackingType { get; set; }

    public virtual PropertyManagement PropertyManagement { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProperytViolation> ProperytViolations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Varience> Variences { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Resident> Residents { get; set; }

}

}
