
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oversii.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class ProperytViolation
{

    public int ProperytViolationID { get; set; }

    public int PropID { get; set; }

    public int ViolationID { get; set; }

    public int AudittrailID { get; set; }



    public virtual Audittrail Audittrail { get; set; }

    public virtual Property Property { get; set; }

    public virtual ViolationList ViolationList { get; set; }

}

}
