
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oversii.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class Resident
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Resident()
    {

        this.Vehicles = new HashSet<Vehicle>();

        this.Addresses = new HashSet<Address>();

    }


    public int ResidentID { get; set; }

    public int PropID { get; set; }

    public int UserID { get; set; }

    public int SubDivisionID { get; set; }

    public string AssignedParkingUnit { get; set; }

    public int StreetID { get; set; }

    public int HouseID { get; set; }



    public virtual House House { get; set; }

    public virtual Street Street { get; set; }

    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Vehicle> Vehicles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Address> Addresses { get; set; }

}

}
