
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Oversii.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class SubDivisionManager
{

    public int SubDivisionManagerID { get; set; }

    public int SubDivisionID { get; set; }

    public int PropID { get; set; }

    public int PropertyManagerID { get; set; }

    public int UserID { get; set; }



    public virtual PropertyManager PropertyManager { get; set; }

    public virtual SubDivision SubDivision { get; set; }

    public virtual User User { get; set; }

}

}
